In [ ]:
from google.colab import files
upload = files.upload()

Saving train_data.csv to train_data (1).csv


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import io
train = pd.read_csv(io.BytesIO(upload['train_data.csv']))
train.head()

id  battery_power  bluetooth  ...  touch_screen  wifi  price_range
0   1            807          1  ...             0     0            1
1   2           1065          1  ...             0     1            2
2   3           1171          1  ...             0     0            0
3   4            609          1  ...             0     1            1
4   5           1193          1  ...             0     0            2

[5 rows x 22 columns]

In [ ]:
train.shape


(1400, 22)

In [ ]:
from google.colab import files 
upload = files.upload()

Saving test_data.csv to test_data.csv


In [ ]:
import io
test = pd.read_csv(io.BytesIO(upload['test_data.csv']))
test.head()

id  battery_power  bluetooth  ...  three_g  touch_screen  wifi
0  1401           1572          1  ...        1             1     1
1  1402            707          0  ...        1             0     1
2  1403            983          0  ...        1             0     1
3  1404            827          1  ...        1             0     1
4  1405           1975          1  ...        0             0     1

[5 rows x 21 columns]

In [ ]:
test.shape

(600, 21)

In [ ]:

#clean the dataset
cleanTrain = train.drop(columns=['id'])
cleanTest = test.drop(columns=['id'])

x_test = cleanTest

x_train = cleanTrain.drop(columns=['price_range'])
y_train = cleanTrain[['price_range']]


In [ ]:
#performing normalization
from sklearn.preprocessing import StandardScaler
#normalized data for train and test here ... split into as much as plb
x_train_scale = StandardScaler().fit_transform(x_train)
x_test_scale = StandardScaler().fit_transform(x_test)

y = np.array(y_train)
y = y.ravel()

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=12)
skf

StratifiedKFold(n_splits=12, random_state=None, shuffle=False)

In [ ]:
for train_data, test_data in skf.split(x_train_scale, y):
  x1_train, x1_test = x_train_scale[train_data], x_train_scale[test_data]
  y1_train, y1_test = y[train_data], y[test_data]

x1_train 

array([[-0.97645183,  1.00142959, -1.24522446, ..., -1.76226327,
        -1.00716855, -1.02458791],
       [-0.39061771,  1.00142959, -1.24522446, ...,  0.5674521 ,
        -1.00716855,  0.97600215],
       [-0.14992617,  1.00142959,  0.21107703, ..., -1.76226327,
        -1.00716855, -1.02458791],
       ...,
       [ 1.70067385, -0.99857245, -1.24522446, ...,  0.5674521 ,
        -1.00716855, -1.02458791],
       [-1.24439146, -0.99857245, -0.15299834, ...,  0.5674521 ,
        -1.00716855, -1.02458791],
       [ 1.33963654,  1.00142959, -0.88114909, ..., -1.76226327,
         0.99288247,  0.97600215]])

In [ ]:
y1_train

array([1, 2, 0, ..., 3, 3, 3])

In [ ]:
x1_test

array([[-0.26118924, -0.99857245, -1.24522446, ...,  0.5674521 ,
         0.99288247, -1.02458791],
       [ 1.28286967, -0.99857245,  1.42466161, ...,  0.5674521 ,
         0.99288247, -1.02458791],
       [-1.61678214,  1.00142959, -1.24522446, ..., -1.76226327,
         0.99288247, -1.02458791],
       ...,
       [-0.46100863,  1.00142959,  1.42466161, ..., -1.76226327,
         0.99288247,  0.97600215],
       [-1.21260201,  1.00142959,  1.42466161, ...,  0.5674521 ,
        -1.00716855, -1.02458791],
       [-0.39288839, -0.99857245,  1.66737852, ...,  0.5674521 ,
        -1.00716855, -1.02458791]])

In [ ]:
model.fit(x1_train, y1_train)  

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_pred = model.predict(x_test_scale)
y_pred

array([3, 3, 1, 1, 3, 3, 0, 0, 2, 3, 1, 1, 0, 1, 0, 1, 2, 1, 3, 2, 3, 2,
       2, 0, 3, 2, 1, 3, 2, 3, 2, 3, 0, 1, 1, 2, 2, 1, 1, 2, 3, 2, 2, 3,
       0, 1, 2, 3, 1, 3, 1, 0, 0, 3, 0, 3, 1, 1, 2, 3, 3, 1, 1, 2, 2, 2,
       1, 2, 0, 0, 0, 1, 0, 3, 3, 0, 2, 1, 0, 2, 1, 2, 1, 3, 0, 2, 0, 2,
       3, 3, 1, 2, 0, 3, 3, 3, 3, 3, 0, 0, 1, 0, 1, 1, 1, 3, 1, 3, 3, 2,
       1, 1, 0, 2, 1, 3, 1, 0, 3, 1, 2, 1, 1, 0, 2, 1, 1, 3, 0, 0, 3, 2,
       0, 0, 0, 0, 1, 2, 1, 2, 3, 0, 2, 0, 3, 3, 0, 3, 2, 0, 3, 1, 2, 3,
       2, 1, 0, 3, 1, 2, 3, 1, 1, 3, 0, 0, 3, 1, 1, 2, 3, 2, 0, 1, 2, 2,
       0, 1, 1, 1, 3, 0, 1, 3, 2, 2, 0, 3, 3, 1, 0, 2, 2, 0, 3, 2, 0, 1,
       3, 3, 0, 1, 1, 3, 3, 0, 2, 3, 0, 2, 3, 0, 3, 3, 1, 1, 3, 1, 2, 2,
       3, 0, 2, 2, 2, 1, 2, 3, 0, 2, 1, 0, 2, 3, 3, 1, 3, 0, 1, 3, 2, 2,
       0, 1, 3, 0, 1, 2, 3, 0, 3, 0, 2, 0, 2, 3, 3, 1, 1, 3, 1, 0, 2, 0,
       3, 2, 2, 2, 2, 2, 1, 2, 3, 1, 0, 3, 0, 2, 1, 2, 3, 2, 1, 3, 3, 1,
       1, 2, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 0, 0, 2,

In [ ]:
submission = pd.DataFrame({'id':test['id'],'price_range':y_predNew})

In [ ]:
submission

In [ ]:
from google.colab import files
submission.to_csv('NewSubmission.csv')
files.download('NewSubmission.csv')